### PR TITLE
Support more formats and upload it to TestPyPI for further tests

### PR DESCRIPTION
**Pull request by li-xin-yi**
*Thanks for your instructions before.*

I modified it to support more export formats. I have tested the feature in a Ubuntu remote server. I also added demonstrations about those new features in README.

For further tests, I upload it to TestPyPi: https://test.pypi.org/project/cfg-explorer/. After you review the pull request, I can also upload it to PyPI officially. If it violates the BSD license, please let me know and I will remove it as soon as possible.

Anyway, I appreciate your awesome work. Thanks.

### CODE REVIEW

**Comment by axt** [comment]
Sorry, for my late answer again! 

I have a remark about the pull request.  When I published angr-utils I've got many critics, because I added the examples file directly to the repository, so anyone who uses that package, needed to download those files too. I personally don't think that a few megabytes matter, but people didn't liked it. I removed them since, and now every image in the angr-utils readmes is linked from imgur. 

What do you think about removing the genetated files from the `example` repository, keeping only the `demo.py`, `demo.pdf`, and `demo.ipynb` files, and then the user can run the demo script to generate those outputs?  

What do you think?

**Comment by li-xin-yi** [comment]
Thanks for such useful advices. 

I will remove the outputs and re-open a pull request later, as I also add some demonstration in `README.MD`. I do understand that the repository itself should be as light as possible.

I'd like to explain that examples will not be packaged into the releases (`.whl` file) on PyPI-Test or PyPI. 

Anyway, no need to worry about the package released.

I will create a new pull request soon. Thanks.

**Comment by axt** [comment]
Thanks for your contribution!

**Comment by axt** [comment]
I've squashed and merged it, so we don't add the removed files to git. 

About the licensing question: I'm not good with licenses, I don't think it will violate anything, so feel free to upload it to pypi.

**Pull request merged**
