### PR TITLE
Release for PyPI. Update readme.md

### PR DESCRIPTION
**Pull request by li-xin-yi**
Thanks for your previous merge work.

I have released the package to [PyPI](https://pypi.org/project/cfg-explorer/) and updated the corresponding installation guide part in `readme.md`.

Somehow, the commit cannot be merged automatically. Can you help me resolve the conflict? I am not good at such tasks.

Thanks anyway.

### CODE REVIEW

**Comment by axt** [comment]
The problem is because I squash-merged your pull request. I never did that before, wasn't aware how it works.

What you can do, to solve the problem. In your local git repository:

Save any local changes:
```
git stash save -u
```

Add my repository as another remote named `upstream`:
```
git remote add upstream https://github.com/axt/cfg-explorer.git
```

Fetch all remotes:
```
git fetch --all
```

Normally you should onyl do this:
```
# git rebase upstream/master
```
but this will not work for now, because i squasmerged your commit.

Instead:

Validate that your previous commit (`master~1`) is in sync with my master (`upsteream/master`)
```
git diff master~1 upstream/master 
```

Rebase your latest commit not already in my repository:
```
git rebase --onto upstream/master master~1 master 
```

Force push (the '+' sign before the branch name) into your remote:
```
git push origin +master
```
I think at this point the pull request will be updated.

Get your stash back:
```
git stash pop
```

**Comment by axt** [comment]
You shoul probably move the tag too:

```
git tag -d v0.0.1
git push --delete origin v0.0.1
```
Then you need to retag, as you did before.

**Comment by li-xin-yi** [comment]
Sorry for late reply.

I think the conflict is already resolved. It's ready to be merged now.

Thanks for your solution.

**Comment by axt** [comment]
Hi! Thanks for the contribution.

Sorry for my late response again! 

I've sent you an invite to give you access to this repository directly. Use it if you want, but if you feel more comfortable sending pull requests in the future, that is also good, I will try to react faster. 

(Still didn't found time to add my ideas :-(. )

**Pull request merged**
